### ISSUE TITLE
Update Homepage

### ISSUE THREAD

**Issue by ppalone** [ppalone/crypt#10]
The Homepage of the website is simple with options to Login & Signup. But, I need something that will match with the project name.

**Comment by shashwatbangar** [comment]
hey, @ppalone it will be my pleasure to work on this project. Can you please assign this to me?

**Comment by ppalone** [comment]
Go ahead.

**Comment by ppalone** [comment]
@shashwatbangar  I haven't heard anything from you.

**Comment by AbhayAysola** [comment]
Looks like this issue is pretty stale, can I work on it? However I need a little more details...

**Comment by ppalone** [comment]
@AbhayAysola Sorry for a late response.
The Homepage of website is very basic with options to login & register. The user first lands on the homepage with they hit the route `https://cryptblog.herokuapp.com`. I was thinking of something that will be attractive and they keep the user hooked for atleast sometime. However @AbhayAysola feel free to use your own ideas. Use anything canvas, animations etc.

**Comment by AbhayAysola** [comment]
All right, I'm no designer but I have a few ideas :)

**Comment by ppalone** [comment]
Take your time.
