### ISSUE TITLE
[Bug] I am unable to register

### ISSUE THREAD

**Issue by AbhayAysola** [ppalone/crypt#12]
I entered my name, email address, password and completed the captcha and clicked Register. After that, the page reloaded and showed me the same screen. I can't register. I'm looking forward ti using this website :)

**Comment by ppalone** [comment]
Did it show any message?

**Comment by AbhayAysola** [comment]
`Please enter a valid password` and no mails

**Comment by ppalone** [comment]
The issue is with validations. It doesn't take passwords with special characters like @, $ etc For eg. `Example@123`. Work around is using password without special characters (But this is definitely not the solution).

**Comment by ppalone** [comment]
I will definitely look into this issue. Thanks for reporting.

**Comment by AbhayAysola** [comment]
All right, thanks for letting me know. I wasn't sure what were the criteria for a password. Maybe accept characters or display a message which shows the criteria for a password.
