### ISSUE TITLE
Resend Verification Email [Bug]

### ISSUE THREAD

**Issue by AbhayAysola** [ppalone/crypt#16]
I signed up, but did not verify the email. After a few days, I tried logging in, but it said that I have to verify my email. Unfortunately, I can't find the verification email. Please add an option to resend the verification email.

**Comment by ppalone** [comment]
This is weird because if the account is not verified it gets deleted after 6 hours and if the email verification mail is not sent, the user is not created in the first place. I'll check the email stats and let you know.

**Comment by AbhayAysola** [comment]
Hmmm, I was messing with the website using a local run. So I think there's something wrong with my side with Sendgrid. My bad, then.
