### ISSUE TITLE
Add validations

### ISSUE THREAD

**Issue by ppalone** [ppalone/crypt#2]
Validating email and password while login & register

**Comment by js899** [comment]
Can i take this issue ? Plz assign it to me

**Comment by ppalone** [comment]
> Also tell which language or technology you want

I'm using Node, Express with EJS templates. Though the values are checked in mongodb, it would be better to tell user that they have put incorrect values. I'm thinking of using express-validators

**Comment by asi309** [comment]
I can take up this issue.

**Comment by ppalone** [comment]
I haven't heard anything from js899. So, feel free @asi309  to go head.

**Comment by Wekananda** [comment]
can you assign me this issue?

**Comment by Gautam-Arora24** [comment]
I can take this issue and can solve it with express-validators. What you say @ppalone ?

**Comment by ppalone** [comment]
Go ahead @Gautam-Arora24

**Comment by Gautam-Arora24** [comment]
Kindly assign it to me @ppalone
