### ISSUE TITLE
Repository not participating in Hacktoberfest

### ISSUE THREAD

**Issue by burzynnn** [ppalone/crypt#8]
# Problem
You marked issues with Hacktoberfest label, but there was an event update introducing new rules, so every new PR doesn't count until you follow [those instructions](https://hacktoberfest.digitalocean.com/hacktoberfest-update).
# Solution
If you want take a look on new rules and adjust repository settings.

**Comment by ppalone** [comment]
Hey @burzynnn, some recent spam PRs during Hacktoberfest 2020 resulted in change of rules in Hacktoberfest. Thanks for letting me know. Actually, this is my first time in hacktoberfest. I'll make changes in repository as per latest rules of hacktoberfest, if I do something wrong please let me know.

**Comment by ppalone** [comment]
I made the changes
- [x] Added `hacktoberfest` topic to project repo
- [x] Labelled the merged PRs as `hacktoberfest-accepted`

Is their anything that I'm missing?

**Comment by burzynnn** [comment]
Everything is fine. I think you can close the issue.

**Comment by ppalone** [comment]
Thanks @burzynnn
